# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = %(here)s/alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Off by default, uncomment to use array of timezone names
# timezone =

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# max length of characters in --autogenerate output
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a corresponding .py file to be detected of value in the revisions directory
# sourceless = false

# version location specification; This defaults to alembic/versions.
# When attempting to method set the version location,
# the default value of alembic/versions is used.
version_locations = %(here)s/alembic/versions

# version path separator; As mentioned above, this is the character used to split
# version_locations. The default value is os.pathsep.
# version_path_separator = :

# set to 'true' to search source tree recursively for revisions
# recursive_version_truncation = false

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
